# This is for git hub auto action to make sure my cron job gets triggered every day

name: Trigger Daily Job Match Cron

on:
  schedule:
    - cron: "41 10 * * *"
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Call match job endpoint
        run: |
          curl -f -X POST https://api.gisteraand.co.za/api/cron/run-match-job \
          -H "x-cron-secret: ${{ secrets.CRON_SECRET }}"
